[vpt] update

diff --git a/project/vc/usr/bin/vpt b/project/vc/usr/bin/vpt
--- a/project/vc/usr/bin/vpt
+++ b/project/vc/usr/bin/vpt
@@ -43,12 +43,12 @@ search_list(){
 	wget -q -O "${tmp_list_file}" $target 2>/dev/null
 	if [ "$?" != 0 ]; then
 		echo "fail to get $target"
-	elif test $# -gt 1; then
-		grep -E "$2" "${tmp_list_file}"
 	else
-		cat "${tmp_list_file}"
-	fi
-	if test -f "${tmp_list_file}"; then
+		if test $# -gt 1; then
+			grep -E "$2" "${tmp_list_file}"
+		else
+			cat "${tmp_list_file}"
+		fi
 		rm "${tmp_list_file}"
 	fi
 }
@@ -58,8 +58,11 @@ install(){
 	if test -f "${tmp_deb_file}"; then
 		rm "${tmp_deb_file}"
 	fi
-	wget -q -O "${tmp_deb_file}" $target 2>/dev/null && dpkg -i "${tmp_deb_file}" || echo "fail to get $target"
-	if test -f "${tmp_deb_file}"; then
+	wget -q -O "${tmp_deb_file}" $target 2>/dev/null
+	if [ "$?" != 0 ]; then
+		echo "fail to get $target"
+	else
+		dpkg -i "${tmp_deb_file}"
 		rm "${tmp_deb_file}"
 	fi
 }
